# Generated by Django 2.1.5 on 2019-01-09 23:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Coordinates',
                'verbose_name_plural': 'Coordinates',
            },
        ),
        migrations.CreateModel(
            name='ScrapingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_scraped', models.BooleanField(default=False)),
                ('scraped_date', models.DateField(auto_now=True)),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Coordinates')),
            ],
            options={
                'verbose_name': 'Scraping Order',
                'verbose_name_plural': 'Scraping Orders',
            },
        ),
        migrations.CreateModel(
            name='Shapefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Shapefile',
                'verbose_name_plural': 'Shapefiles',
            },
        ),
        migrations.AddField(
            model_name='coordinates',
            name='shapefile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Shapefile'),
        ),
    ]
