# Generated by Django 2.1.5 on 2019-01-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190111_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingorder',
            name='status',
            field=models.CharField(choices=[('Waiting', 'waiting'), ('Scraping', 'scraping'), ('Finished', 'finished'), ('No result', 'no_result')], default='waiting', max_length=100),
        ),
    ]
