# Generated by Django 2.1.5 on 2019-01-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190111_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='description',
            field=models.TextField(default='parnaiba', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinates',
            name='title',
            field=models.CharField(default='teresina', max_length=100),
            preserve_default=False,
        ),
    ]
