# Generated by Django 2.1.5 on 2019-01-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190112_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
