# Generated by Django 2.1.5 on 2019-01-15 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190112_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('thumbnail_link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Raster',
                'verbose_name_plural': 'Rasters',
            },
        ),
        migrations.AddField(
            model_name='scrapingorder',
            name='raster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Raster'),
            preserve_default=False,
        ),
    ]
