# Generated by Django 2.1.5 on 2019-01-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190115_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingorder',
            name='raster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Raster'),
        ),
    ]
