# Generated by Django 2.1.5 on 2019-01-16 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_raster_download_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='raster',
            name='download_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
