# Generated by Django 2.1.5 on 2019-02-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190120_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raster',
            name='download_date',
        ),
        migrations.AddField(
            model_name='raster',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapingorder',
            name='status',
            field=models.CharField(choices=[('Waiting', 'waiting'), ('Executing', 'executing'), ('Finished', 'finished'), ('No result', 'no_result')], default='waiting', max_length=100),
        ),
    ]
