# Generated by Django 2.1.5 on 2019-02-12 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190212_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingorder',
            name='raster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Raster'),
        ),
    ]
