# Generated by Django 2.1.5 on 2019-02-12 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190212_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raster',
            name='download_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='raster',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='raster',
            name='thumbnail_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
