# Generated by Django 2.1.5 on 2019-02-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190212_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='raster',
            name='file_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
